disabled_rules: # rule identifiers to exclude from running
  - line_length
  - trailing_newline
  - trailing_whitespace
  - vertical_whitespace
  - for_where
  - opening_brace
  - colon
  - unused_closure_parameter
  - weak_delegate
opt_in_rules: # some rules are only opt-in
  # Find all the available rules by running:
  # swiftlint rules
  force_unwrapping

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
included:
    - GenericConnectionFramework
line_length: 110
# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 500 # error
# or they can set both explicitly
file_length:
  warning: 500
  error: 1200
function_body_length:
  warning: 60
  error: 100
function_parameter_count:
  warning: 8
  error: 12  
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
cyclomatic_complexity: 10
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: # excluded via string
    - ID
variable_name:
  min_length: # only min_length
    error: 3 # only error
  max_length:
    error: 40
  excluded: # excluded via string array
    - x
    - y
    - i
    - j
    - k
    - id
    - app
    - tag
    - moc
    - URL
    - vc
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle)
