# Autogenerated by fastlane
# 
# Ensure this file is checked in to source control!

# frozen_string_literal: true
source "https://rubygems.org"

# adding Danger for GITLAB gem
gem "danger-gitlab"

# adding Swift lint gem
gem 'danger-swiftlint'

# adding mdspell which is a prerequisite for prose
gem 'mdspell'

# adding prose gem
gem 'danger-prose'

# fastlane
gem 'fastlane'

# cocoapods
gem 'cocoapods', '1.7.4'

# Danger for Jenkins
gem "danger-jenkins"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
